### ISSUE TITLE
relationship between schema-registry and chana

### ISSUE THREAD

**Issue by wanghaisheng** [wandoulabs/chana#10]
can Chana used as a schema-registry like thishttps://github.com/confluentinc/schema-registry?
what is the relationship,if i want to use chana as schema-registry,what else i need do?

**Comment by dcaoyuan** [comment]
Not yet, but it's a planned feature. The tasks include: 
 1. store each version of schemas; 
 2. implement an API to put/fetch/delete them (all or specified version). 
 3. The most important (as schema on Chana), when schema changed, should we iterate all related avro records to update to new schema?

**Comment by wanghaisheng** [comment]
thx

**Comment by wanghaisheng** [comment]
if  i want to implement some of these ,where should i  get to start,i can really use your advice
